### ISSUE TITLE
question 3

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/functions-and-variables-quiz#10]
this is the functions and variables quiz ...the answer is wrong because it say that it is 'undefined' in console.. 
but the correct answer is coming up saying that 'log is not function'

**Comment by maxwellbenton** [comment]
Hi @ghost,

Thank you for providing this feedback. We've updated this question to align with the expected output in node as well as repl.it (node results in `undefined`, while repl.it results in `log is not a function`). Both answers are now valid.

Thank you for contributing to this lesson!
