### ISSUE TITLE
Layout is not correct with this lab

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/functions-and-variables-quiz#3]
@pletcher something is not right with this markdown, see below for how this renders in my Chrome:

![screen shot 2016-06-30 at 9 50 31 pm](https://cloud.githubusercontent.com/assets/13033515/16509618/cfeab5fc-3f0c-11e6-9b5d-7773c12d8387.png)

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
I think I forgot the required h1 at the beginning of the quiz?

**Comment by ktravers** [comment]
@pletcher @aturkewi tagging in here so this stays on my radar. likely a parser issue; will investigate this weekend

**Comment by ktravers** [comment]
@pletcher it's the `console.log(x);`. the parser sees `(x)` and interprets it as an answer choice. use literally anything else and you should be fine.
