### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by samnags** [learn-co-curriculum/functions-and-variables-quiz#4]
Q1) Maybe my JS is weak, but shouldn't this hoist greeting?

Perhaps it's the difference between running it in a js file and checking it in the console. 

Q4) Answer is "log is not defined(…)" not "undefined is not undefined"

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
Q1) The variable _declaration_ gets hoisted, but not the assignment -- so that's why it logs "undefined" but doesn't error out.

Q4) Thanks! Will fix :)
