### ISSUE TITLE
Cant figure out the funkyFunction solution

### ISSUE THREAD

**Issue by mikhailalloy** [learn-co-curriculum/functions-and-variables-quiz#6]
I submitted the following:

var funkyFunction = function() {                                                                                                                    
  return function() {                                                                                                                               
    return "FUNKY!"                                                                                                                                 
  }                                                                                                                                                 
}   

// We want 'funkyFunction' on the line below to return a function that returns "FUNKY!" -- how can we accomplish that?
// NOTE: To pass this final test, you only need to modify the code below this line.
var theFunk = funkyFunction ()

Not sure how to solve it

**Comment by jademos** [comment]
After struggling for a while - it may not be the most elegant but it does pass the test

var funkyFunction = function() {
  return function() {
    return "FUNKY!"
  }
}

// We want 'funkyFunction' on the line below to return a function that returns "FUNKY!" -- how can we accomplish that?
// NOTE: To pass this final test, you only need to modify the code below this line.

var theFunk = funkyFunction();
theFunk = theFunk();

**Comment by JessRudder** [comment]
@mikhailalloy please use the "Ask a Question" feature in learn to get help from a Learn Expert.
