### ISSUE TITLE
Console returns undefined

### ISSUE THREAD

**Issue by joshuaneedham** [learn-co-curriculum/functions-and-variables-quiz#7]
When I type the following into the Chrome Console it returns 'undefined' which was the wrong answer for the quiz question #3. I selected undefined as that is what is returned in the console but the apparent correct answer for the question is 'log is not a function'

`log();
var log = function() {
    console.log(greeting);
    var greeting = 'Hello!';
}`

**Comment by gj** [comment]
Hi @joshuaneedham !

The quiz answer is correct.

If you need some assistance understanding why that is, head on over to [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
