### ISSUE TITLE
Incorrect quiz answer?

### ISSUE THREAD

**Issue by humblescuba** [learn-co-curriculum/functions-and-variables-quiz#8]
In the Functions and Variables Quiz, question 3 asserts that 'log is not a function' is the correct answer. However, when you copy and paste the code into the console, all that is returned is 'undefined'. Nowhere in the console does it log that "log is not a function". Here is the code in question:

log();
var log = function() {
  console.log(greeting);
  var greeting = 'Hello!';
}

**Comment by maxwellbenton** [comment]
Hi @humblescuba,

Thank you for providing this feedback. We've updated this question to align with the expected output in node as well as repl.it (node results in `undefined`, repl.it results in `log is not a function`). Both answers are now considered valid.

Thank you for contributing to this lesson!
