### ISSUE TITLE
Question #3

### ISSUE THREAD

**Issue by gasganno** [learn-co-curriculum/functions-and-variables-quiz#9]
When I put the code into console and run it I get undefined, not 'log is not a function'. 

Am I missing something?

<img width="537" alt="screen shot 2017-09-17 at 6 56 53 pm" src="https://user-images.githubusercontent.com/26098882/30525715-05cc360c-9bda-11e7-9ed3-368de05c94d4.png">

**Comment by maxwellbenton** [comment]
Hi @gasganno, 

Thank you for providing this feedback. We've updated this question to align with the expected output in node as well as repl.it (node results in `undefined`, repl.it results in `log is not a function`). Both answers are now considered valid.

Thank you for contributing to this lesson!
